AllCops:
  Exclude:
  - 'vendor/**/*'
  TargetRubyVersion: 2.1

Lint/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Exclude:
  - 'test/**/*'
  Max: 150

Metrics/LineLength:
  Max: 100
  AllowURI: true
  URISchemes:
  - http
  - https

Metrics/MethodLength:
  Max: 20

Style/EmptyLineAfterMagicComment:
  Enabled: false

# When support for Ruby < 2.3 is dropped, re-enable
Style/IndentHeredoc:
  Enabled: false
